using MediatR;
using MerchandisingService.Contracts;

namespace MerchandisingService.Application;

public sealed record CreateBuyerCommand(CreateBuyerRequest Request) : IRequest<BuyerDto>;
public sealed record UpdateBuyerCommand(Guid Id, UpdateBuyerRequest Request) : IRequest<BuyerDto>;
public sealed record ActivateBuyerCommand(Guid Id, bool IsActive) : IRequest<BuyerDto>;
public sealed record CreateSeasonCommand(CreateSeasonRequest Request) : IRequest<SeasonDto>;
public sealed record CreateGarmentItemCommand(CreateGarmentItemRequest Request) : IRequest<GarmentItemDto>;
public sealed record CreateStyleCommand(CreateStyleRequest Request) : IRequest<StyleDto>;
public sealed record UpdateStyleCommand(Guid Id, UpdateStyleRequest Request) : IRequest<StyleDto>;
public sealed record CreateOrderCommand(CreateOrderRequest Request) : IRequest<OrderDto>;
public sealed record UpdateOrderCommand(Guid Id, UpdateOrderRequest Request) : IRequest<OrderDto>;
public sealed record ConfirmOrderCommand(Guid Id) : IRequest<OrderDto>;
public sealed record CancelOrderCommand(Guid Id) : IRequest<OrderDto>;
public sealed record CreateBuyerPoCommand(Guid OrderId, CreateBuyerPoRequest Request) : IRequest<BuyerPurchaseOrderDto>;
public sealed record UpdateBuyerPoCommand(Guid Id, UpdateBuyerPoRequest Request) : IRequest<BuyerPurchaseOrderDto>;
public sealed record CreateColorSizeBreakdownCommand(Guid OrderId, CreateColorSizeBreakdownRequest Request) : IRequest<ColorSizeBreakdownDto>;
public sealed record UpdateColorSizeBreakdownCommand(Guid Id, UpdateColorSizeBreakdownRequest Request) : IRequest<ColorSizeBreakdownDto>;
public sealed record DeleteColorSizeBreakdownCommand(Guid Id) : IRequest<Unit>;
public sealed record CreateBomItemCommand(Guid OrderId, CreateBomItemRequest Request) : IRequest<BomItemDto>;
public sealed record UpdateBomItemCommand(Guid Id, UpdateBomItemRequest Request) : IRequest<BomItemDto>;
public sealed record DeleteBomItemCommand(Guid Id) : IRequest<Unit>;
public sealed record CalculateBomCommand(Guid OrderId) : IRequest<BomCalculationResultDto>;
public sealed record CreateOrderCostingCommand(Guid OrderId, CreateOrderCostingRequest Request) : IRequest<OrderCostingDto>;
public sealed record UpdateOrderCostingCommand(Guid OrderId, CreateOrderCostingRequest Request) : IRequest<OrderCostingDto>;
public sealed record CreateSampleCommand(CreateSampleRequest Request) : IRequest<SampleDto>;
public sealed record ApproveSampleCommand(Guid Id) : IRequest<SampleDto>;
public sealed record RejectSampleCommand(Guid Id) : IRequest<SampleDto>;
public sealed record CreateShipmentPlanCommand(CreateShipmentPlanRequest Request) : IRequest<ShipmentPlanDto>;
public sealed record UpdateShipmentPlanCommand(Guid Id, UpdateShipmentPlanRequest Request) : IRequest<ShipmentPlanDto>;
