// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftService.Infrastructure.Persistence;

#nullable disable

namespace ShiftService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShiftDbContext))]
    [Migration("20260521054337_ShiftPolicyAndEvaluation")]
    partial class ShiftPolicyAndEvaluation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftService.Domain.Entities.EmployeeShiftAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("CompanyId", "EmployeeId")
                        .IsUnique()
                        .HasFilter("[IsCurrent] = 1");

                    b.HasIndex("CompanyId", "EmployeeId", "IsCurrent");

                    b.ToTable("EmployeeShiftAssignments", (string)null);
                });

            modelBuilder.Entity("ShiftService.Domain.Entities.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCrossDay")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGeneralDuty")
                        .HasColumnType("bit");

                    b.Property<int>("PunchWindowBeforeMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60);

                    b.Property<int>("ShiftCategory")
                        .HasColumnType("int");

                    b.Property<string>("ShiftCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "ShiftCode")
                        .IsUnique();

                    b.ToTable("Shifts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1a2b3c4-d5e6-4a7b-8c9d-0e1f2a3b4c5d"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            IsCrossDay = false,
                            IsDefault = true,
                            IsDeleted = false,
                            IsGeneralDuty = true,
                            PunchWindowBeforeMinutes = 60,
                            ShiftCategory = 0,
                            ShiftCode = "UNITY_GENERAL",
                            ShiftName = "Unity General Duty",
                            ShiftType = "GeneralDuty",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            CompanyId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            IsCrossDay = false,
                            IsDefault = true,
                            IsDeleted = false,
                            IsGeneralDuty = true,
                            PunchWindowBeforeMinutes = 60,
                            ShiftCategory = 0,
                            ShiftCode = "EKUSHE_GENERAL",
                            ShiftName = "Ekushe General Duty",
                            ShiftType = "GeneralDuty",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-4a7b-8c9d-0e1f2a3b4c5d"),
                            CompanyId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsActive = true,
                            IsCrossDay = false,
                            IsDefault = false,
                            IsDeleted = false,
                            IsGeneralDuty = false,
                            PunchWindowBeforeMinutes = 60,
                            ShiftCategory = 1,
                            ShiftCode = "DYEING_DAY",
                            ShiftName = "Dyeing Day Shift",
                            ShiftType = "Day",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-4a7b-8c9d-0e1f2a3b4c5d"),
                            CompanyId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EndTime = new TimeSpan(0, 8, 0, 0, 0),
                            IsActive = true,
                            IsCrossDay = true,
                            IsDefault = false,
                            IsDeleted = false,
                            IsGeneralDuty = false,
                            PunchWindowBeforeMinutes = 60,
                            ShiftCategory = 2,
                            ShiftCode = "DYEING_NIGHT",
                            ShiftName = "Dyeing Night Shift",
                            ShiftType = "Night",
                            StartTime = new TimeSpan(0, 20, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("ShiftService.Domain.Entities.ShiftBreak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("BreakEndTime")
                        .HasColumnType("time");

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("int");

                    b.Property<string>("BreakName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("BreakStartTime")
                        .HasColumnType("time");

                    b.Property<int>("BreakType")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaidBreak")
                        .HasColumnType("bit");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftBreaks", (string)null);
                });

            modelBuilder.Entity("ShiftService.Domain.Entities.ShiftCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalendarDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ShiftCalendars", (string)null);
                });

            modelBuilder.Entity("ShiftService.Domain.Entities.ShiftRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowOvertime")
                        .HasColumnType("bit");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeductLunchFromWorking")
                        .HasColumnType("bit");

                    b.Property<int>("EarlyOutBeforeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("HalfDayWorkingMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("HolidayWorkAllAsOvertime")
                        .HasColumnType("bit");

                    b.Property<int>("InGraceMinutes")
                        .HasColumnType("int");

                    b.Property<int>("LateAfterMinutes")
                        .HasColumnType("int");

                    b.Property<int>("LunchBreakMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaximumOvertimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MinimumOvertimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MinimumWorkingMinutes")
                        .HasColumnType("int");

                    b.Property<int>("OutGraceMinutes")
                        .HasColumnType("int");

                    b.Property<int>("OvertimeStartAfterMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WeeklyOffWorkAllAsOvertime")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId")
                        .IsUnique();

                    b.ToTable("ShiftRules", (string)null);
                });

            modelBuilder.Entity("ShiftService.Domain.Entities.TemporaryShiftAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("CompanyId", "EmployeeId", "ShiftDate")
                        .IsUnique();

                    b.ToTable("TemporaryShiftAssignments", (string)null);
                });

            modelBuilder.Entity("ShiftService.Domain.Entities.EmployeeShiftAssignment", b =>
                {
                    b.HasOne("ShiftService.Domain.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftService.Domain.Entities.ShiftBreak", b =>
                {
                    b.HasOne("ShiftService.Domain.Entities.Shift", "Shift")
                        .WithMany("Breaks")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftService.Domain.Entities.ShiftRule", b =>
                {
                    b.HasOne("ShiftService.Domain.Entities.Shift", "Shift")
                        .WithOne("Rule")
                        .HasForeignKey("ShiftService.Domain.Entities.ShiftRule", "ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftService.Domain.Entities.TemporaryShiftAssignment", b =>
                {
                    b.HasOne("ShiftService.Domain.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftService.Domain.Entities.Shift", b =>
                {
                    b.Navigation("Breaks");

                    b.Navigation("Rule");
                });
#pragma warning restore 612, 618
        }
    }
}
