// <auto-generated />
using System;
using CompanyService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CompanyService.Infrastructure.Persistence.Migrations;

[DbContext(typeof(CompanyDbContext))]
[Migration("20260515150000_AddGroupsAndFloors")]
partial class AddGroupsAndFloors
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Target model is captured in CompanyDbContextModelSnapshot.
    }
}
