using AccountsService.Contracts;
using MediatR;

namespace AccountsService.Application;

public sealed record CreateChartOfAccountCommand(CreateChartOfAccountRequest Request) : IRequest<ChartOfAccountDto>;
public sealed record UpdateChartOfAccountCommand(Guid Id, UpdateChartOfAccountRequest Request) : IRequest<ChartOfAccountDto>;
public sealed record SetChartOfAccountActiveCommand(Guid Id, bool IsActive) : IRequest<ChartOfAccountDto>;
public sealed record CreateFiscalYearCommand(CreateFiscalYearRequest Request) : IRequest<FiscalYearDto>;
public sealed record CloseFiscalYearCommand(Guid Id, Guid? ClosedBy) : IRequest<FiscalYearDto>;
public sealed record CreateVoucherCommand(CreateVoucherRequest Request) : IRequest<VoucherDto>;
public sealed record SubmitVoucherCommand(Guid Id, Guid? SubmittedBy) : IRequest<VoucherDto>;
public sealed record ApproveVoucherCommand(Guid Id, Guid? ApprovedBy) : IRequest<VoucherDto>;
public sealed record PostVoucherCommand(Guid Id, Guid? PostedBy) : IRequest<VoucherDto>;
public sealed record CancelVoucherCommand(Guid Id, Guid? CancelledBy) : IRequest<VoucherDto>;
public sealed record CreateCashReceiptCommand(CreateCashReceiptRequest Request) : IRequest<CashReceiptDto>;
public sealed record ApproveCashReceiptCommand(Guid Id, Guid? ApprovedBy) : IRequest<CashReceiptDto>;
public sealed record PostCashReceiptCommand(Guid Id, Guid? PostedBy) : IRequest<CashReceiptDto>;
public sealed record CancelCashReceiptCommand(Guid Id, Guid? CancelledBy) : IRequest<CashReceiptDto>;
public sealed record CreateMoneyReceiptCommand(CreateMoneyReceiptRequest Request) : IRequest<MoneyReceiptDto>;
public sealed record ApproveMoneyReceiptCommand(Guid Id, Guid? ApprovedBy) : IRequest<MoneyReceiptDto>;
public sealed record PostMoneyReceiptCommand(Guid Id, Guid? PostedBy) : IRequest<MoneyReceiptDto>;
public sealed record CreateDailyExpenseCommand(CreateDailyExpenseRequest Request) : IRequest<DailyExpenseDto>;
public sealed record ApproveDailyExpenseCommand(Guid Id, Guid? ApprovedBy) : IRequest<DailyExpenseDto>;
public sealed record PayDailyExpenseCommand(Guid Id, Guid? PaidBy) : IRequest<DailyExpenseDto>;
public sealed record RejectDailyExpenseCommand(Guid Id, Guid? RejectedBy) : IRequest<DailyExpenseDto>;
public sealed record CreateMoneyRequestCommand(CreateMoneyRequestRequest Request) : IRequest<MoneyRequestDto>;
public sealed record ApproveMoneyRequestCommand(Guid Id, ApproveMoneyRequestRequest Request) : IRequest<MoneyRequestDto>;
public sealed record RejectMoneyRequestCommand(Guid Id, Guid? RejectedBy) : IRequest<MoneyRequestDto>;
public sealed record PayMoneyRequestCommand(Guid Id, Guid? PaidBy) : IRequest<MoneyRequestDto>;
public sealed record CreateAdvancePaymentCommand(CreateAdvancePaymentRequest Request) : IRequest<AdvancePaymentDto>;
public sealed record ApproveAdvancePaymentCommand(Guid Id, Guid? ApprovedBy) : IRequest<AdvancePaymentDto>;
public sealed record PayAdvancePaymentCommand(Guid Id, Guid? PaidBy) : IRequest<AdvancePaymentDto>;
public sealed record CreateAdvanceSalaryPaymentCommand(CreateAdvanceSalaryPaymentRequest Request) : IRequest<AdvanceSalaryPaymentDto>;
public sealed record ApproveAdvanceSalaryPaymentCommand(Guid Id, Guid? ApprovedBy) : IRequest<AdvanceSalaryPaymentDto>;
public sealed record PayAdvanceSalaryPaymentCommand(Guid Id, Guid? PaidBy) : IRequest<AdvanceSalaryPaymentDto>;
public sealed record CreateCompanyMoneyTransferCommand(CreateCompanyMoneyTransferRequest Request) : IRequest<CompanyMoneyTransferDto>;
public sealed record ApproveCompanyMoneyTransferCommand(Guid Id, Guid? ApprovedBy) : IRequest<CompanyMoneyTransferDto>;
public sealed record CompleteCompanyMoneyTransferCommand(Guid Id, Guid? TransferredBy) : IRequest<CompanyMoneyTransferDto>;
public sealed record RejectCompanyMoneyTransferCommand(Guid Id, Guid? RejectedBy) : IRequest<CompanyMoneyTransferDto>;
