// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollService.Infrastructure.Persistence;

#nullable disable

namespace PayrollService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20260523043820_PayrollPolicyTemplates")]
    partial class PayrollPolicyTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PayrollService.Domain.Entities.AllowanceBill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowanceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BillDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.ToTable("AllowanceBills", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.CompanyPayrollPolicyAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<decimal?>("FixedOvertimeRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PolicyTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PolicyTemplateId");

                    b.HasIndex("CompanyId", "IsActive")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("CompanyPayrollPolicyAssignments", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.EmployeePayroll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AbsentDays")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AbsentDeduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AdvanceDeduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AppliedPolicyCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("AppliedPolicySnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppliedPolicyVersion")
                        .HasColumnType("int");

                    b.Property<decimal>("AttendanceBonusAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BasicSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConveyanceAllowance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EarnLeaveEncashmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FestivalBonusAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FoodAllowance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HolidayPresentDays")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HouseRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LateDays")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LateDeduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LeaveDays")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LeaveWithoutPayDays")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoanDeduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MedicalAllowance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MonthNo")
                        .HasColumnType("int");

                    b.Property<decimal>("NetSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NightBillAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherDeduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OvertimeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OvertimeCalculationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("OvertimeHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OvertimeRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PayrollRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PresentDays")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProcessingMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ProvidentFundDeduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SalaryCalculationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Draft");

                    b.Property<decimal>("TaxDeduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TiffinBillAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDays")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalEarnings")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalOvertimeMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("WeeklyOffPresentDays")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WorkingDays")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YearNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "EmployeeId", "YearNo", "MonthNo")
                        .IsUnique();

                    b.ToTable("EmployeePayrolls", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.EmployeeSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasicSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConveyanceAllowance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FoodAllowance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HouseRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<decimal>("MedicalAllowance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SalaryCalculationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Monthly");

                    b.Property<Guid?>("SalaryStructureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "EmployeeId", "IsCurrent")
                        .IsUnique()
                        .HasFilter("[IsCurrent] = 1");

                    b.ToTable("EmployeeSalaries", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.FinalSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdvanceDeduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EarnLeaveAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GratuityAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("LastWorkingDate")
                        .HasColumnType("date");

                    b.Property<decimal>("NetPayable")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherDeduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaryPayable")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServiceBenefitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("SettlementDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.ToTable("FinalSettlements", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.PayrollAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("PayrollAuditLogs", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.PayrollDeduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeductionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeductionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("EmployeePayrollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsManual")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeePayrollId");

                    b.ToTable("PayrollDeductions", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.PayrollDeductionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeductionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MonthNo")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Approved");

                    b.Property<int>("YearNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PayrollDeductionEntries", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.PayrollEarning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EarningCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EarningName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("EmployeePayrollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsManual")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeePayrollId");

                    b.ToTable("PayrollEarnings", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.PayrollPolicyTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AbsentBase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AbsentDayDivisor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("AllowAbsentDeduction")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowAttendanceBonus")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowEarnLeaveEncashment")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowFestivalBonus")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowLateDeduction")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowNightBill")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowOvertime")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowTiffinBill")
                        .HasColumnType("bit");

                    b.Property<decimal>("BasicDivisor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ComplianceMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FixedAbsentDays")
                        .HasColumnType("int");

                    b.Property<decimal>("FixedConveyance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedFood")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedMedical")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FixedMonthDays")
                        .HasColumnType("int");

                    b.Property<string>("MonthDayCalculationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OtBase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("OtDivisor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtMultiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PolicyCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RequireAttendanceApproval")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyCode")
                        .IsUnique();

                    b.ToTable("PayrollPolicyTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000001"),
                            AbsentBase = "Basic",
                            AbsentDayDivisor = "FixedDays",
                            AllowAbsentDeduction = true,
                            AllowAttendanceBonus = false,
                            AllowEarnLeaveEncashment = true,
                            AllowFestivalBonus = true,
                            AllowLateDeduction = false,
                            AllowNightBill = false,
                            AllowOvertime = true,
                            AllowTiffinBill = false,
                            BasicDivisor = 1.5m,
                            ComplianceMode = "FullCompliance",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FixedAbsentDays = 30,
                            FixedConveyance = 450m,
                            FixedFood = 1250m,
                            FixedMedical = 750m,
                            FixedMonthDays = 30,
                            MonthDayCalculationType = "FixedDays",
                            OtBase = "Basic",
                            OtDivisor = 208m,
                            OtMultiplier = 2m,
                            PolicyCode = "BDT_COMPLIANCE_V1",
                            PolicyName = "Bangladesh Full Compliance Salary Rule",
                            RequireAttendanceApproval = true,
                            Status = "Active",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a1000002-0000-0000-0000-000000000002"),
                            AbsentBase = "Gross",
                            AbsentDayDivisor = "CalendarDays",
                            AllowAbsentDeduction = true,
                            AllowAttendanceBonus = false,
                            AllowEarnLeaveEncashment = true,
                            AllowFestivalBonus = true,
                            AllowLateDeduction = false,
                            AllowNightBill = false,
                            AllowOvertime = true,
                            AllowTiffinBill = false,
                            BasicDivisor = 1.5m,
                            ComplianceMode = "NonCompliance",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FixedAbsentDays = 30,
                            FixedConveyance = 450m,
                            FixedFood = 1250m,
                            FixedMedical = 750m,
                            FixedMonthDays = 30,
                            MonthDayCalculationType = "CalendarDays",
                            OtBase = "Gross",
                            OtDivisor = 208m,
                            OtMultiplier = 2m,
                            PolicyCode = "BDT_NONCOMPLIANCE_GROSS_OT_V1",
                            PolicyName = "Non-Compliance Gross OT",
                            RequireAttendanceApproval = false,
                            Status = "Active",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a1000003-0000-0000-0000-000000000003"),
                            AbsentBase = "Gross",
                            AbsentDayDivisor = "CalendarDays",
                            AllowAbsentDeduction = true,
                            AllowAttendanceBonus = false,
                            AllowEarnLeaveEncashment = true,
                            AllowFestivalBonus = true,
                            AllowLateDeduction = false,
                            AllowNightBill = false,
                            AllowOvertime = true,
                            AllowTiffinBill = false,
                            BasicDivisor = 1.5m,
                            ComplianceMode = "NonCompliance",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FixedAbsentDays = 30,
                            FixedConveyance = 450m,
                            FixedFood = 1250m,
                            FixedMedical = 750m,
                            FixedMonthDays = 30,
                            MonthDayCalculationType = "CalendarDays",
                            OtBase = "Gross",
                            OtDivisor = 240m,
                            OtMultiplier = 1.5m,
                            PolicyCode = "BDT_NONCOMPLIANCE_GROSS240_OT_V1",
                            PolicyName = "Non-Compliance Gross 240 OT",
                            RequireAttendanceApproval = false,
                            Status = "Active",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a1000004-0000-0000-0000-000000000004"),
                            AbsentBase = "Gross",
                            AbsentDayDivisor = "CalendarDays",
                            AllowAbsentDeduction = true,
                            AllowAttendanceBonus = false,
                            AllowEarnLeaveEncashment = true,
                            AllowFestivalBonus = true,
                            AllowLateDeduction = false,
                            AllowNightBill = false,
                            AllowOvertime = true,
                            AllowTiffinBill = false,
                            BasicDivisor = 1.5m,
                            ComplianceMode = "NonCompliance",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FixedAbsentDays = 30,
                            FixedConveyance = 450m,
                            FixedFood = 1250m,
                            FixedMedical = 750m,
                            FixedMonthDays = 30,
                            MonthDayCalculationType = "CalendarDays",
                            OtBase = "Fixed",
                            OtDivisor = 208m,
                            OtMultiplier = 2m,
                            PolicyCode = "BDT_NONCOMPLIANCE_FIXED_OT_V1",
                            PolicyName = "Non-Compliance Fixed OT Rate",
                            RequireAttendanceApproval = false,
                            Status = "Active",
                            Version = 1
                        });
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.PayrollRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppliedPolicyCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("AppliedPolicyVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedEmployees")
                        .HasColumnType("int");

                    b.Property<decimal?>("FixedOvertimeRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MonthNo")
                        .HasColumnType("int");

                    b.Property<string>("OvertimeCalculationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProcessedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProcessedEmployees")
                        .HasColumnType("int");

                    b.Property<string>("ProcessingMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RunNo")
                        .HasColumnType("int");

                    b.Property<string>("RunStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalEmployees")
                        .HasColumnType("int");

                    b.Property<int>("YearNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "YearNo", "MonthNo", "RunNo")
                        .IsUnique();

                    b.ToTable("PayrollRuns", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.SalaryAdvance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdvanceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("AdvanceDate")
                        .HasColumnType("date");

                    b.Property<string>("AdvanceNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BalanceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeductionStartMonth")
                        .HasColumnType("int");

                    b.Property<int>("DeductionStartYear")
                        .HasColumnType("int");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InstallmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("RequestedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "AdvanceNo")
                        .IsUnique();

                    b.ToTable("SalaryAdvances", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.SalaryAdvanceInstallment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeePayrollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InstallmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MonthNo")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SalaryAdvanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("YearNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalaryAdvanceId", "YearNo", "MonthNo")
                        .IsUnique();

                    b.ToTable("SalaryAdvanceInstallments", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.SalaryIncrementRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("IncrementAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncrementPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewBasicSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewGrossSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldBasicSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldGrossSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.ToTable("SalaryIncrementRequests", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.SalaryStructure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StructureCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StructureName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "StructureCode")
                        .IsUnique();

                    b.ToTable("SalaryStructures", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.SalaryStructureComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BasedOnComponentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("bit");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SalaryStructureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SalaryStructureId", "ComponentCode")
                        .IsUnique();

                    b.ToTable("SalaryStructureComponents", (string)null);
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.CompanyPayrollPolicyAssignment", b =>
                {
                    b.HasOne("PayrollService.Domain.Entities.PayrollPolicyTemplate", "PolicyTemplate")
                        .WithMany()
                        .HasForeignKey("PolicyTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PolicyTemplate");
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.PayrollDeduction", b =>
                {
                    b.HasOne("PayrollService.Domain.Entities.EmployeePayroll", null)
                        .WithMany("Deductions")
                        .HasForeignKey("EmployeePayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.PayrollEarning", b =>
                {
                    b.HasOne("PayrollService.Domain.Entities.EmployeePayroll", null)
                        .WithMany("Earnings")
                        .HasForeignKey("EmployeePayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.SalaryAdvanceInstallment", b =>
                {
                    b.HasOne("PayrollService.Domain.Entities.SalaryAdvance", null)
                        .WithMany("Installments")
                        .HasForeignKey("SalaryAdvanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.SalaryStructureComponent", b =>
                {
                    b.HasOne("PayrollService.Domain.Entities.SalaryStructure", null)
                        .WithMany("Components")
                        .HasForeignKey("SalaryStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.EmployeePayroll", b =>
                {
                    b.Navigation("Deductions");

                    b.Navigation("Earnings");
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.SalaryAdvance", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("PayrollService.Domain.Entities.SalaryStructure", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
